// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const envUrl = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim() || "";
const envKey = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim() || "";

/** Default local Supabase API URL (`supabase start`). */
const DEV_FALLBACK_URL = "http://127.0.0.1:54321";
/**
 * Public anon key from Supabase local dev template. Only used when env vars are missing so
 * `createClient` does not throw at import time (avoids a blank app before React mounts).
 */
const DEV_FALLBACK_ANON =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

if (!envUrl || !envKey) {
  if (import.meta.env.DEV) {
    console.warn(
      "[Margin6] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY is not set. Using local dev fallbacks. " +
        "Add them to `.env` (see `.env.example`) or run `supabase start` to match 127.0.0.1:54321.",
    );
  } else {
    console.error(
      "[Margin6] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Set them in the hosting project env; auth and data will not work until set.",
    );
  }
}

const SUPABASE_URL = envUrl || (import.meta.env.DEV ? DEV_FALLBACK_URL : "https://missing-env.supabase.co");
const SUPABASE_PUBLISHABLE_KEY = envKey || (import.meta.env.DEV ? DEV_FALLBACK_ANON : "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoicHVibGljX2Fub25fZGV2In0.missing");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});